# Generated by Django 4.2.7 on 2026-06-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='mobile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='banners/'),
        ),
    ]
