# Generated by Django 4.2.7 on 2026-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_herobanner_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
