# Generated by Django 4.2.7 on 2026-06-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_herobanner_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(max_length=500, upload_to='banners/mobile/')),
                ('alt', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='mobile_image',
        ),
    ]
