# Generated by Django 4.2.7 on 2026-06-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_mobilebanner_remove_herobanner_mobile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='product',
            name='razorpay_buy_now_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
