# Generated by Django 6.0.6 on 2026-06-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='label',
            field=models.CharField(default='Home', max_length=100),
        ),
    ]
