# Generated by Django 6.0.6 on 2026-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
